spring.application.name=main-service
server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5433/library_service
spring.datasource.username=${USERNAME}
spring.datasource.password=${PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.instance.prefer-ip-address=true
grpc.client.recomendation-service.address=static://recomendation-service:9090
grpc.client.recomendation-service.negotiationType=plaintext
