

services:

  postgres:
    image: postgres:16
    container_name: library-postgres
    environment:
      POSTGRES_DB: library_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Eugesha2005
    ports:
      - "5433:5432"


  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 10


  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"


  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/


  main-service:
    build: ./main-service
    container_name: main-service
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - rabbitmq
      - eureka-server
    environment:

      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/library_service
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Eugesha2005
      - SPRING_RABBITMQ_HOST=rabbitmq
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/

  notification-service:
    build: ./notification-service
    container_name: notification-service
    ports:
      - "8082:8082"
    depends_on:
      - rabbitmq
      - eureka-server
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/

  recomendation-service:
    build: ./recomendation-service
    container_name: recomendation-service
    ports:
      - "8083:8083"
      - "9090:9090"

    depends_on:
      - eureka-server

    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/